version: 2.1

# workflows:
#   version: 2
#   main:
#     jobs:
#       - build:
#           filters:
#             branches:
#               only: master

jobs:
  build:
    docker:
      - image: circleci/node:14.9.0-buster

    working_directory: ~/application

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Webpack JS files
          command: CI= npm run build

      - run:
          name: Build docker image
          command: docker build -t bricefrisco/eccshopdb-frontend:$CIRCLE_BUILD_NUM .

      - run:
          name: Push docker image
          command: docker push bricefrisco/eccshopdb-frontend:$CIRCLE_BUILD_NUM

      - run:
          name: Deploy to server
          command: scp -o StrictHostKeyChecking=no $HOST -r build root@$HOST:/var/www/html
