version: 2.1

workflows:
  version: 2
  main:
    jobs:
      - build_test:
          filters:
            branches:
              only: test

      - build:
          filters:
            branches:
              only: master

jobs:
  build_test:
    docker:
      - image: circleci/node:14.9.0-buster

    working_directory: ~/application

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Webpack JS files
          command: CI= npm run build

      - run:
          name: Deploy to server
          command: scp -o StrictHostKeyChecking=no -r /home/circleci/application/build/* $TEST_HOST:/var/www/html

  build:
    docker:
      - image: circleci/node:14.9.0-buster

    working_directory: ~/application

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Webpack JS files
          command: CI= npm run build

      - run:
          name: Deploy to server
          command: scp -o StrictHostKeyChecking=no -r /home/circleci/application/build/* root@$HOST:/var/www/html
